### ISSUE TITLE
希望能显示每次更新的时间

### ISSUE THREAD

**Issue by MarsCloud** [Nikaidou-Shinku/dophelia#2]
![image](https://github.com/user-attachments/assets/705a27fc-06d3-4577-8f79-3575db642d01)
如图，目前可以统计作者在某个时间段内的更新次数，但并不能看到原子数据长什么样，所以希望能在这张活跃表上鼠标悬停时，能够显示当天更新的时间（有可能一天会出现多更的情况，需要分开显示）

**Comment by Nikaidou-Shinku** [comment]
由于 Cal-Heatmap 的限制，实现这个可能有些困难。

**Comment by Nikaidou-Shinku** [comment]
Added since v0.3.1.
