### ISSUE TITLE
更新显示可以有小小的优化

### ISSUE THREAD

**Issue by MarsCloud** [Nikaidou-Shinku/dophelia#3]
![Screenshot_2024-09-01-23-54-36-63_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/3d72fbed-6e4d-4d41-8b24-f31990bc4dce)
![Screenshot_2024-09-01-23-54-45-80_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/c98138bd-5399-454a-9315-0fcdc8b868b9)
如图上所示，此日的更新是请假条，但是在更新显示中视为进行了一次更新，这显然对催更功能的定义不一致。
所以可能的优化方式有这么几种：首先是检测更新章节是否为付费章节，然后再检测该章节字数是否足够（比如，1000字以上才算一次正常的更新？），如果不是正常更新，那么这个催更信息栏就不认可本次更新。

**Comment by Nikaidou-Shinku** [comment]
虽然咕了很久但是补上了！目前统计最近更新时间时忽略字数少于 1000 字的章节。

**Comment by Nikaidou-Shinku** [comment]
Added since v0.3.2.
